### ISSUE TITLE
Basic prompt stopped working

### ISSUE THREAD

**Issue by ashish10alex** [jackMort/ChatGPT.nvim#101] opened 2023-03-14 06:15 UTC
Hi, 
The ChatGPT plugin has all of a sudden stopped working. It gives the following error when I give it a prompt

Neovim version details
```
➜  ~/.config/nvim nvim --version
NVIM v0.9.0-dev-2433+g3e8955094-dirty
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-3e89550/share/nvim"
```

<img width="1440" alt="CleanShot 2023-03-14 at 11 36 34@2x" src="https://user-images.githubusercontent.com/34306898/224911601-4e8428fc-4898-42bc-9c89-e4592914e51f.png">

**Comment by cmpadden** [comment] 2023-04-06 17:40
This appears to be a duplicate of this issue: https://github.com/jackMort/ChatGPT.nvim/issues/128

Are you also using `jiangmiao/auto-pairs` like @Leo310? https://github.com/jackMort/ChatGPT.nvim/issues/128#issuecomment-1494817538

> TF, for whatever reason this [plugin](https://github.com/jiangmiao/auto-pairs) was causing the issue.
Not sure if this is worth investigating so you can close the issue from my side.
> 
> For those with the same problem, I switched to https://github.com/windwp/nvim-autopairs

**Comment by ashish10alex** [comment] 2023-04-06 18:04
Thanks @cmpadden , removing the plugin `jiangmiao/auto-pairs` seems to have fixed the issue.

**Closed** 2023-06-11 11:59 UTC

**Comment by tomaszwostal** [comment] 2023-08-10 19:10
> This appears to be a duplicate of this issue: #128
> 
> Are you also using `jiangmiao/auto-pairs` like @Leo310? [#128 (comment)](https://github.com/jackMort/ChatGPT.nvim/issues/128#issuecomment-1494817538)
> 
> > TF, for whatever reason this [plugin](https://github.com/jiangmiao/auto-pairs) was causing the issue.
> > Not sure if this is worth investigating so you can close the issue from my side.
> > For those with the same problem, I switched to https://github.com/windwp/nvim-autopairs
