### ISSUE TITLE
<C-y> yanking last question and not last answer

### ISSUE THREAD

**Issue by MattiasKockum** [jackMort/ChatGPT.nvim#3] opened 2022-12-15 05:52 UTC
As I get it, in ChatGPT.nvim/lua/chatgpt/module.lua on line 45-46, it yanks the message into "+
Problem is the message yanked is the last question, not ast answer

**Comment by jackMort** [comment] 2022-12-15 06:05
Is this occurs in a specific case or all the times?

**Comment by MattiasKockum** [comment] 2022-12-15 17:14
All the times, I can never yank the last answer

**Comment by jackMort** [comment] 2022-12-15 19:08
Alright, that's weird, but I need to add some logging to debug that, I cant reproduce it

**Comment by MattiasKockum** [comment] 2022-12-15 21:46
My config is this one (just copied the init file then add your use command)
https://www.youtube.com/watch?v=ctH-a-1eUME&list=PLhoH5vyxr6Qq41NFL4GvhFp-WLd5xzIzZ

**Comment by MattiasKockum** [comment] 2022-12-15 22:34
[solved]
My bad sorry, I did not connect my nvim config with any clipboard, so I guess the mistake was coming from that since it's solved now.
Still don't understand why it pasted the last question in the neovim register but nevermind.

**Comment by jackMort** [comment] 2022-12-15 23:18
cool, thanks for the information. I'm closing this one, but I'll keep it in mind in case of similar problems in the future.

**Closed by jackMort** 2022-12-15 23:18 UTC

**Comment by cuducos** [comment] 2023-02-04 20:10
Same here. Would you mind clarifying what you mean by _ I did not connect my nvim config with any clipboard_, @MattiasKockum?

What I yank on Neovim goes to my system's clipboard. Still, `C-y` on the ChatGPT plugin copies the question, not the answer…
