### ISSUE TITLE
how to fix '53 // API ERROR: The model: `code-davinci-001` does not exist'

### ISSUE THREAD

**Issue by liangsj** [jackMort/ChatGPT.nvim#122] opened 2023-03-24 04:28 UTC
how to fix '53 // API ERROR: The model: `code-davinci-001` does not exist'

**Comment by DGmip** [comment] 2023-03-24 09:03
OpenAI said they were getting rid of that model in favour of GPT3.5, maybe it's that

**Comment by linulas** [comment] 2023-03-24 09:11
> OpenAI said they were getting rid of that model in favour of GPT3.5, maybe it's that

Yes, It seems to be that, also relates to: #120

**Comment by 00sapo** [comment] 2023-03-24 11:16
Moving to gpt-3.5-turbo should be rather, but some change to the API call must be implemented in the code, I guess

**Comment by cmpadden** [comment] 2023-03-24 16:38
I find myself referring to the playground to see which models are currently supported. API documentation doesn't seem to be up-to-date.

https://platform.openai.com/playground?mode=chat

![image](https://user-images.githubusercontent.com/5807118/227586744-81ec8d01-2844-4e24-8a7a-23c4f2b6e66d.png)

**Comment by 00sapo** [comment] 2023-03-24 17:06
This plugin is using edit and completion mode, mainly. Thwy removed davinci-code so you can still use the generic models.We can't still use gpt-3.5-turbo, because that needs a rewrite of the interface to the OpenAI API

**Comment by liangsj** [comment] 2023-03-27 02:25
so . i think this neovim plugin can not work util Open Ai support . it is so sad ~~~LOL~~

**Comment by cmpadden** [comment] 2023-03-31 14:40
I can confirm that things are working well, and that the model is available. I'd say that this issue could be closed.

List of available `code` models for reference:

```bash
$ models=$(curl -s https://api.openai.com/v1/models -H "Authorization: Bearer $OPENAI_API_KEY")
$ jq -r .data[].id  <(echo "$models") | sort | grep code
ada-code-search-code
ada-code-search-text
babbage-code-search-code
babbage-code-search-text
code-davinci-edit-001
code-search-ada-code-001
code-search-ada-text-001
code-search-babbage-code-001
code-search-babbage-text-001
```

**Closed** 2023-04-03 09:42 UTC

**Comment by Leo310** [comment] 2023-04-03 20:33
Is the model offline again?
![image](https://user-images.githubusercontent.com/48623649/229620815-464e645c-1c8b-4c23-af14-c7336e692a85.png)

I am not even sure why it uses "code-davinci-002" because my config uses "code-davinci-edit-001"

**Comment by Leo310** [comment] 2023-04-06 17:45
@cmpadden @jackMort maybe reopen this issue? Problem still exists on my side

**Comment by cmpadden** [comment] 2023-04-06 17:54
> @cmpadden @jackMort maybe reopen this issue? Problem still exists on my side

I say open it.

I need to look into the code some more to better understand if the configured model overrides the ones defined here, but it's possible `code-davinci-002` is hard-coded in a few places. (First time looking at this part of the code).

```
> grep code-davinci-002
lua/chatgpt/flows/code_completions/init.lua
55:    model = "code-davinci-002",

lua/chatgpt/flows/actions/init.lua
102:          model = "code-davinci-002",

lua/chatgpt/flows/actions/actions.json
44:        "model": "code-davinci-002",
57:        "model": "code-davinci-002",
69:        "model": "code-davinci-002",
90:        "model": "code-davinci-002",
103:        "model": "code-davinci-002",
```

**Comment by cmpadden** [comment] 2023-04-07 14:05
@Leo310 it appears all references to `code-davinci-002` are overwritten with what is defined in `openai_edit_params`:

```
                openai_edit_params = {
                    model = "code-davinci-edit-001",
                    temperature = 0,
                    top_p = 1,
                    n = 1,
                },
```

Are you sure you have this defined? I get the same error as you when I set `model = "code-davinci-002"`, but it works as expected with `model = "code-davinci-edit-001"`.

**Comment by Leo310** [comment] 2023-04-07 14:15
Yeah now it works. Just updated to the latest version :+1:. 

But the visualization/implementation could be improved. For example, the code explanation replaces the source code I want to understand instead of displaying it in a popup or something. But that's a different topic.

**Comment by cmpadden** [comment] 2023-04-07 14:35
Definitely agree that it could use some refinements, but glad it's working for you now! 👍
