### ISSUE TITLE
Token cost covers last bit of the answer

### ISSUE THREAD

**Issue by matthis-k** [jackMort/ChatGPT.nvim#69] opened 2023-02-01 15:08 UTC
![image](https://user-images.githubusercontent.com/69082876/216080438-8ec92456-c669-47e5-bbea-89491cdf8549.png)

With the image I think the problem is rather clear, the token and cost should not cover some part of the answer, maybe just move it one line down?

**Comment by mattiasbonte** [comment] 2023-02-03 11:37
duplicate of #66

**Closed** 2023-02-04 18:40 UTC
